### ISSUE TITLE
const any_invocable seems to be uninvokable

### ISSUE THREAD

**Issue by krnowak** [ofats/any_invocable#7]
Not sure if this is an issue with the implementation or I did something wrong.

Trying to invoke `const ofats::any_invocable<void()>` or `const ofats::any_invocable<void() const>` results in compilation errors. The former because matching call operator could not be found, the latter is because `any_invocable_impl::call` doesn't have a `const` variant. Please see an example on godbolt: https://godbolt.org/z/Wczddnsoh

The `const` qualifier comes from being a member of a class and being invoked in const function, like:

```c++
struct stuff
{
  void call() const { f(); }
  ofats::any_invocable<void()> f; // or `void() const`
}
```

**Comment by ofats** [comment]
Hi

Looking at example code you provided, it works as expected. `any_invocable` without `const` qualifier for its callable type is expected to be able to mutate itself when calling its `operator()` (which is achieved by having only non-const `operator()` in `any_invocable` class definition for non-const callable type). That's why you cannot use it in `const` member function of containing outer class.

To make this code work, either `f` should have `const` for it's callable type, or `call()` should not have `const`.

Looking now at godbolt example more.

**Comment by ofats** [comment]
I see the problem, will make fixing PR shortly.

**Comment by ofats** [comment]
Your example at https://godbolt.org/z/Wczddnsoh builds now.
